<?PHP
$pages = array(
"start" => "start.php",
"error" => "error.php",
"users" => "users.php",
"user" => "user.php",
"save" => "save.php",
"delete" => "delete.php",
"menus" => "menus.php",
"menu" => "menu.php",
"pages" => "pages.php",
"page" => "page.php",
"news" => "news.php",
"new" => "new.php",
"documents" => "documents.php",
"uploadfile" => "uploadfile.php",
"my-settings" => "usersettings.php",
"general-settings" => "generalsettings.php",
"themes" => "themes.php",
"plugins" => "plugins.php",
"pluginactions" => "pluginactions.php",
"plugin" => "plugin.php",
"themeplugin" => "themeplugin.php",
"logout" => "logout.php",
"update" => "updateCMS.php",
"updatelog" => "updatelog.php",
"update-result" => "updateresult.php",
"form" => "form.php",
"forms" => "forms.php",
"form_result" => "form_result.php",
"form_results" => "form_results.php",
);
?>